In [8]:
#Question 1
import numpy as np
array=np.array([1,2,3,4,5,6])
print (array)
print(type(array))
print(array.tolist())
print(type(array.tolist()))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
<class 'list'>


In [18]:
#Question 2
array=np.eye(3,4,dtype=int)
print(array)
print(array[0,0]+array[1,1]+array[2,2]) #manual way
print(array)
new_array=np.trace(array) #using trace function
print(new_array)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
3
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
3


In [88]:
#Question 3
a = np.array([[1,2],[3,4]])
b = a>2
print(a[b])

[3 4]


In [32]:
#Question 4
a=np.array([1,2])
b=np.array([3,4])
c=a+b
print(c)

[4 6]


In [71]:
#Question 5
a=np.array([[1,2],[3,4],[5,6]])
a.reshape(2,3)
print(a)
b=np.mean(a,axis=0)
print(b)
c=a-b

[[1 2]
 [3 4]
 [5 6]]
[3. 4.]
